function [output] = applyChannel(modulatedSignal, SNR, rayleighSettings)
    noisySignal = awgn(modulatedSignal,SNR,'measured');
    
    rayChan = comm.RayleighChannel( ...
    'SampleRate',          rayleighSettings.Fs, ...
    'PathDelays',          rayleighSettings.pathDelays, ...
    'AveragePathGains',    rayleighSettings.avgPathGains, ...
    'MaximumDopplerShift', rayleighSettings.maxDopplerShift, ...
    'RandomStream',        'mt19937ar with seed', ...
    'Seed',                10, ...
    'PathGainsOutputPort', true);

    output = rayChan(noisySignal);
end