% Generated by MATLAB(R) 9.8 (R2020a) and Communications Toolbox 7.3 (R2020a).
% Generated on: 13-Jan-2021 16:40:02
% Updated by Ronny Milleo
function [output] = generate_psk(M,L,SPS,SNR,phase)
%% Generate PSK Waveform
% input bit source:
if M == 2
    in = randi([0, 1], (L + 8), 1);
elseif M == 4
    in = randi([0, 1], (L + 8)*2, 1);
elseif M == 8
    in = randi([0, 1], (L + 8)*3, 1);
end
usedInput = in(1:log2(M)*(floor(length(in)/log2(M))));
tmp = reshape(usedInput, log2(M), length(usedInput)/log2(M));
symbolInput = bi2de(tmp', 'left-msb');

% waveform generation:
phaseOffset = pi/M;
waveform = pskmod(symbolInput, M, phaseOffset, 'gray');

% filtering:
rcFilter = comm.RaisedCosineTransmitFilter('Shape', 'Square root', ...
    'RolloffFactor', 0.25, ...
    'OutputSamplesPerSymbol', SPS, ...
    'FilterSpanInSymbols', 10);
waveform = rcFilter(waveform);
%% Impair QAM Waveform
% Random phase
%rand_phase = pi*(2*rand(1)-1); % -pi to pi

% Phase Offset
waveform = waveform * exp(1i*phase);

% AWGN
waveform = awgn(waveform, SNR, 'measured');

% Normalize power to 0 dB
waveform = waveform / rms(waveform);
output = waveform(65:end);
end